/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AzureLocation = "westus" | "australiaeast" | "southeastasia" | "northeurope";

/**
 * extra section in app.json
 */
export interface Extra {
  /**
   * Semantic Version
   */
  semver: string;
  /**
   * Show Hint when idle for x seconds
   */
  showHintIdleSeconds: number;
  /**
   * Show interstitial ad every x calls
   */
  showInterstitialCalls: number;
  /**
   * Maximium calls when failed to load ad
   */
  limitedAccessCalls: number;
  /**
   * AdMob Settings
   */
  adMobSettings: {
    banners: AdUnitIds[];
    interstitials: AdUnitIds[];
    testDeviceIds: string[];
  };
  /**
   * Geo and azure location mapping
   */
  geoAzureLocationMap: {
    AF?: "westus" | "australiaeast" | "southeastasia" | "northeurope";
    AN?: "westus" | "australiaeast" | "southeastasia" | "northeurope";
    AS?: "westus" | "australiaeast" | "southeastasia" | "northeurope";
    EU?: "westus" | "australiaeast" | "southeastasia" | "northeurope";
    NA?: "westus" | "australiaeast" | "southeastasia" | "northeurope";
    OC?: "westus" | "australiaeast" | "southeastasia" | "northeurope";
    SA?: "westus" | "australiaeast" | "southeastasia" | "northeurope";
  };
  /**
   * Face api endpoints and keys
   */
  faceApiKeys: ApiLocationKey[];
  /**
   * Emotion api endpoints and keys
   */
  emotionApiKeys: ApiLocationKey[];
  /**
   * Vision api endpoints and keys
   */
  visionApiKeys: ApiLocationKey[];
}
export interface AdUnitIds {
  ios?: string;
  android?: string;
}
export interface ApiLocationKey {
  location: AzureLocation;
  key: string;
}
